# **CV analysis**

In [1]:
import re
import spacy
import nltk
import pandas as pd
nltk.download('punkt')
nlp = spacy.load('en_core_web_sm')
print("📌 جميع المكتبات تم تحميلها بنجاح!")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

📌 جميع المكتبات تم تحميلها بنجاح!

In [3]:
skills_df = pd.read_csv("newSkills.csv", encoding='utf-8', on_bad_lines='skip')
majors_df = pd.read_csv("majors.csv", encoding='utf-8')

In [5]:
skills_df

                    Text            Entities
0                 Python   [(0, 6, 'SKILL')]
1                   Java   [(0, 4, 'SKILL')]
2                    C++   [(0, 3, 'SKILL')]
3             JavaScript  [(0, 10, 'SKILL')]
4                     C#   [(0, 1, 'SKILL')]
..                   ...                 ...
871         CAD modeling  [(0, 11, 'SKILL')]
872  Autodesk Fusion 360  [(0, 19, 'SKILL')]
873              Arduino   [(0, 6, 'SKILL')]
874                   OS   [(0, 1, 'SKILL')]
875                  GUI   [(0, 2, 'SKILL')]

[876 rows x 2 columns]

In [4]:
majors_df.head()

                                   Major                   Major_Category
0                    GENERAL AGRICULTURE  Agriculture & Natural Resources
1  AGRICULTURE PRODUCTION AND MANAGEMENT  Agriculture & Natural Resources
2                 AGRICULTURAL ECONOMICS  Agriculture & Natural Resources
3                        ANIMAL SCIENCES  Agriculture & Natural Resources
4                           FOOD SCIENCE  Agriculture & Natural Resources

In [7]:
#nlp = spacy.blank("en")
#TRAIN_DATA = []
#TRAIN_DATA = [(text.strip(), {"entities": [(0, len(text.strip()), "SKILL")]}) for text in skills_df["Text"]]
#print(TRAIN_DATA)

[('Python', {'entities': [(0, 6, 'SKILL')]}), ('Java', {'entities': [(0, 4, 'SKILL')]}), ('C++', {'entities': [(0, 3, 'SKILL')]}), ('JavaScript', {'entities': [(0, 10, 'SKILL')]}), ('C#', {'entities': [(0, 2, 'SKILL')]}), ('Ruby', {'entities': [(0, 4, 'SKILL')]}), ('Swift', {'entities': [(0, 5, 'SKILL')]}), ('Kotlin', {'entities': [(0, 6, 'SKILL')]}), ('Go', {'entities': [(0, 2, 'SKILL')]}), ('TypeScript', {'entities': [(0, 10, 'SKILL')]}), ('HTML5', {'entities': [(0, 5, 'SKILL')]}), ('CSS3', {'entities': [(0, 4, 'SKILL')]}), ('React', {'entities': [(0, 5, 'SKILL')]}), ('Angular', {'entities': [(0, 7, 'SKILL')]}), ('Vue.js', {'entities': [(0, 6, 'SKILL')]}), ('Node.js', {'entities': [(0, 7, 'SKILL')]}), ('Express.js', {'entities': [(0, 10, 'SKILL')]}), ('Django', {'entities': [(0, 6, 'SKILL')]}), ('Flask', {'entities': [(0, 5, 'SKILL')]}), ('RESTful APIs', {'entities': [(0, 12, 'SKILL')]}), ('SQL', {'entities': [(0, 3, 'SKILL')]}), ('MySQL', {'entities': [(0, 5, 'SKILL')]}), ('PostgreSQL', {'entities': [(0, 10, 'SKILL')]}), ('MongoDB', {'entities': [(0, 7, 'SKILL')]}), ('Oracle', {'entities': [(0, 6, 'SKILL')]}), ('SQLite', {'entities': [(0, 6, 'SKILL')]}), ('NoSQL', {'entities': [(0, 5, 'SKILL')]}), ('Linux/Unix', {'entities': [(0, 10, 'SKILL')]}), ('Windows Server', {'entities': [(0, 14, 'SKILL')]}), ('macOS', {'entities': [(0, 5, 'SKILL')]}), ('Git', {'entities': [(0, 3, 'SKILL')]}), ('GitHub', {'entities': [(0, 6, 'SKILL')]}), ('GitLab', {'entities': [(0, 6, 'SKILL')]}), ('Bitbucket', {'entities': [(0, 9, 'SKILL')]}), ('Docker', {'entities': [(0, 6, 'SKILL')]}), ('Kubernetes', {'entities': [(0, 10, 'SKILL')]}), ('Jenkins', {'entities': [(0, 7, 'SKILL')]}), ('Ansible', {'entities': [(0, 7, 'SKILL')]}), ('Terraform', {'entities': [(0, 9, 'SKILL')]}), ('Amazon Web Services (AWS)', {'entities': [(0, 25, 'SKILL')]}), ('Microsoft Azure', {'entities': [(0, 15, 'SKILL')]}), ('Google Cloud Platform (GCP)', {'entities': [(0, 27, 'SKILL')]}), ('Android Development (Java/Kotlin)', {'entities': [(0, 33, 'SKILL')]}), ('iOS Development (Swift)', {'entities': [(0, 23, 'SKILL')]}), ('Network Security', {'entities': [(0, 16, 'SKILL')]}), ('Ethical Hacking', {'entities': [(0, 15, 'SKILL')]}), ('Cryptography', {'entities': [(0, 12, 'SKILL')]}), ('Security Protocols', {'entities': [(0, 18, 'SKILL')]}), ('Penetration Testing', {'entities': [(0, 19, 'SKILL')]}), ('NumPy', {'entities': [(0, 5, 'SKILL')]}), ('Pandas', {'entities': [(0, 6, 'SKILL')]}), ('Matplotlib', {'entities': [(0, 10, 'SKILL')]}), ('Scikit-learn', {'entities': [(0, 12, 'SKILL')]}), ('TensorFlow', {'entities': [(0, 10, 'SKILL')]}), ('PyTorch', {'entities': [(0, 7, 'SKILL')]}), ('Data Analysis', {'entities': [(0, 13, 'SKILL')]}), ('Natural Language Processing (NLP)', {'entities': [(0, 33, 'SKILL')]}), ('Sorting Algorithms', {'entities': [(0, 18, 'SKILL')]}), ('Searching Algorithms', {'entities': [(0, 20, 'SKILL')]}), ('Graph Theory', {'entities': [(0, 12, 'SKILL')]}), ('Dynamic Programming', {'entities': [(0, 19, 'SKILL')]}), ('Agile', {'entities': [(0, 5, 'SKILL')]}), ('Scrum', {'entities': [(0, 5, 'SKILL')]}), ('Kanban', {'entities': [(0, 6, 'SKILL')]}), ('Object-Oriented Programming (OOP)', {'entities': [(0, 33, 'SKILL')]}), ('Functional Programming', {'entities': [(0, 22, 'SKILL')]}), ('Event-Driven Programming', {'entities': [(0, 24, 'SKILL')]}), ('WebSockets', {'entities': [(0, 10, 'SKILL')]}), ('GraphQL', {'entities': [(0, 7, 'SKILL')]}), ('WebAssembly', {'entities': [(0, 11, 'SKILL')]}), ('Apache', {'entities': [(0, 6, 'SKILL')]}), ('Nginx', {'entities': [(0, 5, 'SKILL')]}), ('Tomcat', {'entities': [(0, 6, 'SKILL')]}), ('JUnit', {'entities': [(0, 5, 'SKILL')]}), ('Selenium', {'entities': [(0, 8, 'SKILL')]}), ('Jest', {'entities': [(0, 4, 'SKILL')]}), ('Continuous Integration', {'entities': [(0, 22, 'SKILL')]}), ('Continuous Deployment', {'entities': [(0, 21, 'SKILL')]}), ('OpenAPI', {'entities': [(0, 7, 'SKILL')]}), ('Postman', {'entities': [(0, 7, 'SKILL')]}), ('TCP/IP', {'entities': [(0, 6, 'SKILL')]}), ('DNS', {'entities': [(0, 3, 'SKILL')]}), ('HTTP/HTTPS', {'entities': [(0, 10, 'SKILL')]}), ('VPN', {'entities': [(0, 3, 'SKILL')]}), ('Spring (Java)', {'entities': [(0, 13, 'SKILL')]}), ('Django (Python)', {'entities': [(0, 15, 'SKILL')]}), ('Ruby on Rails', {'entities': [(0, 13, 'SKILL')]}), ('Flask (Python)', {'entities': [(0, 14, 'SKILL')]}), ('Visual Studio Code', {'entities': [(0, 18, 'SKILL')]}), ('IntelliJ IDEA', {'entities': [(0, 13, 'SKILL')]}), ('Eclipse', {'entities': [(0, 7, 'SKILL')]}), ('Jira', {'entities': [(0, 4, 'SKILL')]}), ('Trello', {'entities': [(0, 6, 'SKILL')]}), ('Asana', {'entities': [(0, 5, 'SKILL')]}), ('Communication', {'entities': [(0, 13, 'SKILL')]}), ('Problem-Solving', {'entities': [(0, 15, 'SKILL')]}), ('Team Collaboration', {'entities': [(0, 18, 'SKILL')]}), ('Time Management', {'entities': [(0, 15, 'SKILL')]}), ('Adaptability', {'entities': [(0, 12, 'SKILL')]}), ('Shell scripting', {'entities': [(0, 15, 'SKILL')]}), ('D3.js (Data-Driven Documents)', {'entities': [(0, 29, 'SKILL')]}), ('Redux (State management for JavaScript apps)', {'entities': [(0, 44, 'SKILL')]}), ('Xamarin (Cross-platform mobile app development)', {'entities': [(0, 47, 'SKILL')]}), ('Flask-RESTful (RESTful API development in Python)', {'entities': [(0, 49, 'SKILL')]}), ('BigQuery (Google Cloud data warehouse)', {'entities': [(0, 38, 'SKILL')]}), ('Hadoop', {'entities': [(0, 6, 'SKILL')]}), ('MapReduce', {'entities': [(0, 9, 'SKILL')]}), ('Apache Kafka (Distributed streaming platform)', {'entities': [(0, 45, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('GraphQL (Query language for APIs)', {'entities': [(0, 33, 'SKILL')]}), ('Redux-Saga (Middleware library for Redux)', {'entities': [(0, 41, 'SKILL')]}), ('Electron (Cross-platform desktop app development)', {'entities': [(0, 49, 'SKILL')]}), ('Polymer (JavaScript library for building web components)', {'entities': [(0, 56, 'SKILL')]}), ('Rust (Programming language focused on performance and safety)', {'entities': [(0, 61, 'SKILL')]}), ('Clojure (Functional programming language)', {'entities': [(0, 41, 'SKILL')]}), ('Elm (Functional programming language for front-end development)', {'entities': [(0, 63, 'SKILL')]}), ('Meteor (Full-stack JavaScript framework)', {'entities': [(0, 40, 'SKILL')]}), ('Apache Spark (Distributed computing)', {'entities': [(0, 36, 'SKILL')]}), ('RxJS (Reactive programming in JavaScript)', {'entities': [(0, 41, 'SKILL')]}), ('Blockchain development', {'entities': [(0, 22, 'SKILL')]}), ('Solidity (Programming language for smart contracts)', {'entities': [(0, 51, 'SKILL')]}), ('Apache Cordova (Mobile app development using web technologies)', {'entities': [(0, 62, 'SKILL')]}), ('Flask-SQLAlchemy (SQL toolkit for Python)', {'entities': [(0, 41, 'SKILL')]}), ('GraphQL Yoga (Fully-featured GraphQL server)', {'entities': [(0, 44, 'SKILL')]}), ('Firebase (Mobile and web application development platform)', {'entities': [(0, 58, 'SKILL')]}), ('Amazon DynamoDB (NoSQL database)', {'entities': [(0, 32, 'SKILL')]}), ('Apache Cassandra (Distributed NoSQL database)', {'entities': [(0, 45, 'SKILL')]}), ('Neo4j (Graph database)', {'entities': [(0, 22, 'SKILL')]}), ('Microsoft SQL Server', {'entities': [(0, 20, 'SKILL')]}), ('Heroku (Cloud platform as a service)', {'entities': [(0, 36, 'SKILL')]}), ('PaaS (Platform as a Service)', {'entities': [(0, 28, 'SKILL')]}), ('Serverless architecture', {'entities': [(0, 23, 'SKILL')]}), ('Microservices architecture', {'entities': [(0, 26, 'SKILL')]}), ('Istio (Service mesh)', {'entities': [(0, 20, 'SKILL')]}), ('AWS Lambda (Serverless computing)', {'entities': [(0, 33, 'SKILL')]}), ('Jupyter Notebooks (Interactive computing and data visualization)', {'entities': [(0, 64, 'SKILL')]}), ('R programming language', {'entities': [(0, 22, 'SKILL')]}), ('Julia (Programming language for technical computing)', {'entities': [(0, 52, 'SKILL')]}), ('Grafana (Open-source analytics and monitoring platform)', {'entities': [(0, 55, 'SKILL')]}), ('Prometheus (Monitoring and alerting toolkit)', {'entities': [(0, 44, 'SKILL')]}), ('Splunk (Data analysis and visualization)', {'entities': [(0, 40, 'SKILL')]}), ('Kibana (Data visualization tool)', {'entities': [(0, 32, 'SKILL')]}), ('Grafana (Open-source analytics and monitoring platform)', {'entities': [(0, 55, 'SKILL')]}), ('Zeppelin (Web-based notebook for data analytics)', {'entities': [(0, 48, 'SKILL')]}), ('Data warehousing', {'entities': [(0, 16, 'SKILL')]}), ('Power BI (Business analytics tool)', {'entities': [(0, 34, 'SKILL')]}), ('Tableau (Data visualization and business intelligence)', {'entities': [(0, 54, 'SKILL')]}), ('Snowflake (Cloud-based data warehousing)', {'entities': [(0, 40, 'SKILL')]}), ('Augmented Reality (AR)', {'entities': [(0, 22, 'SKILL')]}), ('Virtual Reality (VR)', {'entities': [(0, 20, 'SKILL')]}), ('Computer vision', {'entities': [(0, 15, 'SKILL')]}), ('Natural Language Generation (NLG)', {'entities': [(0, 33, 'SKILL')]}), ('Automated Speech Recognition (ASR)', {'entities': [(0, 34, 'SKILL')]}), ('Computer-aided design (CAD)', {'entities': [(0, 27, 'SKILL')]}), ('Cyber-physical systems', {'entities': [(0, 22, 'SKILL')]}), ('Quantum computing', {'entities': [(0, 17, 'SKILL')]}), ('Web scraping', {'entities': [(0, 12, 'SKILL')]}), ('RESTful design principles', {'entities': [(0, 25, 'SKILL')]}), ('GraphQL mutations', {'entities': [(0, 17, 'SKILL')]}), ('OAuth (Authorization framework)', {'entities': [(0, 31, 'SKILL')]}), ('OpenID Connect (Authentication on top of OAuth)', {'entities': [(0, 47, 'SKILL')]}), ('JSON Web Tokens (JWT)', {'entities': [(0, 21, 'SKILL')]}), ('OAuth2.0', {'entities': [(0, 8, 'SKILL')]}), ('OpenID Connect (OIDC)', {'entities': [(0, 21, 'SKILL')]}), ('WebAuthn (Web Authentication API)', {'entities': [(0, 33, 'SKILL')]}), ('JWT (JSON Web Tokens)', {'entities': [(0, 21, 'SKILL')]}), ('OAuth (Open Authorization)', {'entities': [(0, 26, 'SKILL')]}), ('OAuth2.0 (Authorization framework)', {'entities': [(0, 34, 'SKILL')]}), ('OpenID Connect (Authentication on top of OAuth)', {'entities': [(0, 47, 'SKILL')]}), ('Firebase Authentication', {'entities': [(0, 23, 'SKILL')]}), ('Single Sign-On (SSO)', {'entities': [(0, 20, 'SKILL')]}), ('Two-Factor Authentication (2FA)', {'entities': [(0, 31, 'SKILL')]}), ('FIDO2 (WebAuthn)', {'entities': [(0, 16, 'SKILL')]}), ('Identity and Access Management (IAM)', {'entities': [(0, 36, 'SKILL')]}), ('RBAC (Role-Based Access Control)', {'entities': [(0, 32, 'SKILL')]}), ('ABAC (Attribute-Based Access Control)', {'entities': [(0, 37, 'SKILL')]}), ('CQRS (Command Query Responsibility Segregation)', {'entities': [(0, 47, 'SKILL')]}), ('Event Sourcing', {'entities': [(0, 14, 'SKILL')]}), ('Micro Frontends', {'entities': [(0, 15, 'SKILL')]}), ('Progressive Web Apps (PWAs)', {'entities': [(0, 27, 'SKILL')]}), ('Single Page Applications (SPAs)', {'entities': [(0, 31, 'SKILL')]}), ('WebAssembly (Wasm)', {'entities': [(0, 18, 'SKILL')]}), ('OpenAPI Specification', {'entities': [(0, 21, 'SKILL')]}), ('SOAP (Simple Object Access Protocol)', {'entities': [(0, 36, 'SKILL')]}), ('GraphQL subscriptions', {'entities': [(0, 21, 'SKILL')]}), ('Server-Sent Events (SSE)', {'entities': [(0, 24, 'SKILL')]}), ('WebSockets', {'entities': [(0, 10, 'SKILL')]}), ('Webhooks', {'entities': [(0, 8, 'SKILL')]}), ('Application Performance Monitoring (APM)', {'entities': [(0, 40, 'SKILL')]}), ('Log management', {'entities': [(0, 14, 'SKILL')]}), ('Error tracking', {'entities': [(0, 14, 'SKILL')]}), ('Distributed tracing', {'entities': [(0, 19, 'SKILL')]}), ('Chaos engineering', {'entities': [(0, 17, 'SKILL')]}), ('Load balancing', {'entities': [(0, 14, 'SKILL')]}), ('Critical Thinking', {'entities': [(0, 17, 'SKILL')]}), ('Problem-Solving', {'entities': [(0, 15, 'SKILL')]}), ('Decision Making', {'entities': [(0, 15, 'SKILL')]}), ('Analytical Skills', {'entities': [(0, 17, 'SKILL')]}), ('Creativity', {'entities': [(0, 10, 'SKILL')]}), ('Innovation', {'entities': [(0, 10, 'SKILL')]}), ('Adaptability', {'entities': [(0, 12, 'SKILL')]}), ('Time Management', {'entities': [(0, 15, 'SKILL')]}), ('Organization', {'entities': [(0, 12, 'SKILL')]}), ('Prioritization', {'entities': [(0, 14, 'SKILL')]}), ('Communication', {'entities': [(0, 13, 'SKILL')]}), ('Collaboration', {'entities': [(0, 13, 'SKILL')]}), ('Teamwork', {'entities': [(0, 8, 'SKILL')]}), ('Leadership', {'entities': [(0, 10, 'SKILL')]}), ('Conflict Resolution', {'entities': [(0, 19, 'SKILL')]}), ('Emotional Intelligence', {'entities': [(0, 22, 'SKILL')]}), ('Empathy', {'entities': [(0, 7, 'SKILL')]}), ('Active Listening', {'entities': [(0, 16, 'SKILL')]}), ('Presentation Skills', {'entities': [(0, 19, 'SKILL')]}), ('Public Speaking', {'entities': [(0, 15, 'SKILL')]}), ('Negotiation', {'entities': [(0, 11, 'SKILL')]}), ('Networking', {'entities': [(0, 10, 'SKILL')]}), ('Customer Service', {'entities': [(0, 16, 'SKILL')]}), ('Client Management', {'entities': [(0, 17, 'SKILL')]}), ('Relationship Building', {'entities': [(0, 21, 'SKILL')]}), ('Cultural Sensitivity', {'entities': [(0, 20, 'SKILL')]}), ('Ethics', {'entities': [(0, 6, 'SKILL')]}), ('Integrity', {'entities': [(0, 9, 'SKILL')]}), ('Initiative', {'entities': [(0, 10, 'SKILL')]}), ('Self-Motivation', {'entities': [(0, 15, 'SKILL')]}), ('Learning Agility', {'entities': [(0, 16, 'SKILL')]}), ('Flexibility', {'entities': [(0, 11, 'SKILL')]}), ('Resilience', {'entities': [(0, 10, 'SKILL')]}), ('Stress Management', {'entities': [(0, 17, 'SKILL')]}), ('Interpersonal Skills', {'entities': [(0, 20, 'SKILL')]}), ('Cross-Cultural Competence', {'entities': [(0, 25, 'SKILL')]}), ('Business Acumen', {'entities': [(0, 15, 'SKILL')]}), ('Project Management', {'entities': [(0, 18, 'SKILL')]}), ('Risk Management', {'entities': [(0, 15, 'SKILL')]}), ('Quality Assurance', {'entities': [(0, 17, 'SKILL')]}), ('Conflict Management', {'entities': [(0, 19, 'SKILL')]}), ('Change Management', {'entities': [(0, 17, 'SKILL')]}), ('Decision-Making', {'entities': [(0, 15, 'SKILL')]}), ('Financial Literacy', {'entities': [(0, 18, 'SKILL')]}), ('Entrepreneurship', {'entities': [(0, 16, 'SKILL')]}), ('Business Development', {'entities': [(0, 20, 'SKILL')]}), ('Sales Skills', {'entities': [(0, 12, 'SKILL')]}), ('Marketing', {'entities': [(0, 9, 'SKILL')]}), ('Customer Relationship Management (CRM)', {'entities': [(0, 38, 'SKILL')]}), ('Strategic Planning', {'entities': [(0, 18, 'SKILL')]}), ('Data Literacy', {'entities': [(0, 13, 'SKILL')]}), ('Digital Literacy', {'entities': [(0, 16, 'SKILL')]}), ('Information Literacy', {'entities': [(0, 20, 'SKILL')]}), ('Research Skills', {'entities': [(0, 15, 'SKILL')]}), ('Technical Writing', {'entities': [(0, 17, 'SKILL')]}), ('Documentation', {'entities': [(0, 13, 'SKILL')]}), ('Report Writing', {'entities': [(0, 14, 'SKILL')]}), ('Blogging', {'entities': [(0, 8, 'SKILL')]}), ('Public Relations', {'entities': [(0, 16, 'SKILL')]}), ('Time Tracking', {'entities': [(0, 13, 'SKILL')]}), ('Goal Setting', {'entities': [(0, 12, 'SKILL')]}), ('Delegation', {'entities': [(0, 10, 'SKILL')]}), ('Motivational Skills', {'entities': [(0, 19, 'SKILL')]}), ('Cross-Functional Collaboration', {'entities': [(0, 30, 'SKILL')]}), ('Stakeholder Management', {'entities': [(0, 22, 'SKILL')]}), ('Feedback and Coaching', {'entities': [(0, 21, 'SKILL')]}), ('Mentoring', {'entities': [(0, 9, 'SKILL')]}), ('Knowledge Sharing', {'entities': [(0, 17, 'SKILL')]}), ('Training and Development', {'entities': [(0, 24, 'SKILL')]}), ('Conflict Resolution', {'entities': [(0, 19, 'SKILL')]}), ('Facilitation Skills', {'entities': [(0, 19, 'SKILL')]}), ('Decision Making Under Pressure', {'entities': [(0, 30, 'SKILL')]}), ('Attention to Detail', {'entities': [(0, 19, 'SKILL')]}), ('Project Coordination', {'entities': [(0, 20, 'SKILL')]}), ('Crisis Management', {'entities': [(0, 17, 'SKILL')]}), ('Strategic Thinking', {'entities': [(0, 18, 'SKILL')]}), ('Systems Thinking', {'entities': [(0, 16, 'SKILL')]}), ('Forecasting', {'entities': [(0, 11, 'SKILL')]}), ('Trend Analysis', {'entities': [(0, 14, 'SKILL')]}), ('Presentation Design', {'entities': [(0, 19, 'SKILL')]}), ('Data Visualization', {'entities': [(0, 18, 'SKILL')]}), ('Storytelling', {'entities': [(0, 12, 'SKILL')]}), ('Cultural Intelligence', {'entities': [(0, 21, 'SKILL')]}), ('Social Media Management', {'entities': [(0, 23, 'SKILL')]}), ('Community Building', {'entities': [(0, 18, 'SKILL')]}), ('Volunteerism', {'entities': [(0, 12, 'SKILL')]}), ('Time Blocking', {'entities': [(0, 13, 'SKILL')]}), ('Goal Setting', {'entities': [(0, 12, 'SKILL')]}), ('Continuous Improvement', {'entities': [(0, 22, 'SKILL')]}), ('Team Building', {'entities': [(0, 13, 'SKILL')]}), ('Appreciative Inquiry', {'entities': [(0, 20, 'SKILL')]}), ('User-Centered Design', {'entities': [(0, 20, 'SKILL')]}), ('User Experience (UX) Design', {'entities': [(0, 27, 'SKILL')]}), ('User Interface (UI) Design', {'entities': [(0, 26, 'SKILL')]}), ('Human-Computer Interaction (HCI)', {'entities': [(0, 32, 'SKILL')]}), ('Design Thinking', {'entities': [(0, 15, 'SKILL')]}), ('Agile Methodology', {'entities': [(0, 17, 'SKILL')]}), ('Scrum', {'entities': [(0, 5, 'SKILL')]}), ('Kanban', {'entities': [(0, 6, 'SKILL')]}), ('Lean Thinking', {'entities': [(0, 13, 'SKILL')]}), ('Racket (Lisp dialect)', {'entities': [(0, 21, 'SKILL')]}), ('Julia (Programming language for technical computing)', {'entities': [(0, 52, 'SKILL')]}), ('Shell scripting', {'entities': [(0, 15, 'SKILL')]}), ('WebRTC (Real-Time Communication)', {'entities': [(0, 32, 'SKILL')]}), ('NATS (Messaging system)', {'entities': [(0, 23, 'SKILL')]}), ('CockroachDB (Distributed SQL database)', {'entities': [(0, 38, 'SKILL')]}), ('InfluxDB (Open-source time-series database)', {'entities': [(0, 43, 'SKILL')]}), ('ArangoDB (Multi-model NoSQL database)', {'entities': [(0, 37, 'SKILL')]}), ('Flink (Stream processing framework)', {'entities': [(0, 35, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('Celery (Distributed task queue)', {'entities': [(0, 31, 'SKILL')]}), ('Redis (In-memory data structure store)', {'entities': [(0, 38, 'SKILL')]}), ('GraphQL subscriptions', {'entities': [(0, 21, 'SKILL')]}), ('GRPC (Remote procedure call framework)', {'entities': [(0, 38, 'SKILL')]}), ('Protocol Buffers', {'entities': [(0, 16, 'SKILL')]}), ('Flutter (UI toolkit for building natively compiled applications)', {'entities': [(0, 64, 'SKILL')]}), ('Xamarin (Cross-platform mobile app development)', {'entities': [(0, 47, 'SKILL')]}), ('Unity (Game development)', {'entities': [(0, 24, 'SKILL')]}), ('Godot Engine (Open-source game development)', {'entities': [(0, 43, 'SKILL')]}), ('Rust (Programming language focused on performance and safety)', {'entities': [(0, 61, 'SKILL')]}), ('ClojureScript (Clojure compiler for JavaScript)', {'entities': [(0, 47, 'SKILL')]}), ('Elm (Functional programming language for front-end development)', {'entities': [(0, 63, 'SKILL')]}), ('Meteor (Full-stack JavaScript framework)', {'entities': [(0, 40, 'SKILL')]}), ('Puppet (Configuration management tool)', {'entities': [(0, 38, 'SKILL')]}), ('Chef (Infrastructure automation framework)', {'entities': [(0, 42, 'SKILL')]}), ('Pulumi (Infrastructure as code)', {'entities': [(0, 31, 'SKILL')]}), ('HashiCorp Vault (Secrets management)', {'entities': [(0, 36, 'SKILL')]}), ('Cockpit (Linux server management)', {'entities': [(0, 33, 'SKILL')]}), ('Apache Kafka Streams (Stream processing library)', {'entities': [(0, 48, 'SKILL')]}), ('Logstash (Server-side data processing pipeline)', {'entities': [(0, 47, 'SKILL')]}), ('Kibana (Data visualization tool)', {'entities': [(0, 32, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('NATS (Messaging system)', {'entities': [(0, 23, 'SKILL')]}), ('Fluentd (Open-source data collector)', {'entities': [(0, 36, 'SKILL')]}), ('ArgoCD (GitOps continuous delivery tool

In [8]:
#print(TRAIN_DATA)

[('Python', {'entities': [(0, 6, 'SKILL')]}), ('Java', {'entities': [(0, 4, 'SKILL')]}), ('C++', {'entities': [(0, 3, 'SKILL')]}), ('JavaScript', {'entities': [(0, 10, 'SKILL')]}), ('C#', {'entities': [(0, 2, 'SKILL')]}), ('Ruby', {'entities': [(0, 4, 'SKILL')]}), ('Swift', {'entities': [(0, 5, 'SKILL')]}), ('Kotlin', {'entities': [(0, 6, 'SKILL')]}), ('Go', {'entities': [(0, 2, 'SKILL')]}), ('TypeScript', {'entities': [(0, 10, 'SKILL')]}), ('HTML5', {'entities': [(0, 5, 'SKILL')]}), ('CSS3', {'entities': [(0, 4, 'SKILL')]}), ('React', {'entities': [(0, 5, 'SKILL')]}), ('Angular', {'entities': [(0, 7, 'SKILL')]}), ('Vue.js', {'entities': [(0, 6, 'SKILL')]}), ('Node.js', {'entities': [(0, 7, 'SKILL')]}), ('Express.js', {'entities': [(0, 10, 'SKILL')]}), ('Django', {'entities': [(0, 6, 'SKILL')]}), ('Flask', {'entities': [(0, 5, 'SKILL')]}), ('RESTful APIs', {'entities': [(0, 12, 'SKILL')]}), ('SQL', {'entities': [(0, 3, 'SKILL')]}), ('MySQL', {'entities': [(0, 5, 'SKILL')]}), ('PostgreSQL', {'entities': [(0, 10, 'SKILL')]}), ('MongoDB', {'entities': [(0, 7, 'SKILL')]}), ('Oracle', {'entities': [(0, 6, 'SKILL')]}), ('SQLite', {'entities': [(0, 6, 'SKILL')]}), ('NoSQL', {'entities': [(0, 5, 'SKILL')]}), ('Linux/Unix', {'entities': [(0, 10, 'SKILL')]}), ('Windows Server', {'entities': [(0, 14, 'SKILL')]}), ('macOS', {'entities': [(0, 5, 'SKILL')]}), ('Git', {'entities': [(0, 3, 'SKILL')]}), ('GitHub', {'entities': [(0, 6, 'SKILL')]}), ('GitLab', {'entities': [(0, 6, 'SKILL')]}), ('Bitbucket', {'entities': [(0, 9, 'SKILL')]}), ('Docker', {'entities': [(0, 6, 'SKILL')]}), ('Kubernetes', {'entities': [(0, 10, 'SKILL')]}), ('Jenkins', {'entities': [(0, 7, 'SKILL')]}), ('Ansible', {'entities': [(0, 7, 'SKILL')]}), ('Terraform', {'entities': [(0, 9, 'SKILL')]}), ('Amazon Web Services (AWS)', {'entities': [(0, 25, 'SKILL')]}), ('Microsoft Azure', {'entities': [(0, 15, 'SKILL')]}), ('Google Cloud Platform (GCP)', {'entities': [(0, 27, 'SKILL')]}), ('Android Development (Java/Kotlin)', {'entities': [(0, 33, 'SKILL')]}), ('iOS Development (Swift)', {'entities': [(0, 23, 'SKILL')]}), ('Network Security', {'entities': [(0, 16, 'SKILL')]}), ('Ethical Hacking', {'entities': [(0, 15, 'SKILL')]}), ('Cryptography', {'entities': [(0, 12, 'SKILL')]}), ('Security Protocols', {'entities': [(0, 18, 'SKILL')]}), ('Penetration Testing', {'entities': [(0, 19, 'SKILL')]}), ('NumPy', {'entities': [(0, 5, 'SKILL')]}), ('Pandas', {'entities': [(0, 6, 'SKILL')]}), ('Matplotlib', {'entities': [(0, 10, 'SKILL')]}), ('Scikit-learn', {'entities': [(0, 12, 'SKILL')]}), ('TensorFlow', {'entities': [(0, 10, 'SKILL')]}), ('PyTorch', {'entities': [(0, 7, 'SKILL')]}), ('Data Analysis', {'entities': [(0, 13, 'SKILL')]}), ('Natural Language Processing (NLP)', {'entities': [(0, 33, 'SKILL')]}), ('Sorting Algorithms', {'entities': [(0, 18, 'SKILL')]}), ('Searching Algorithms', {'entities': [(0, 20, 'SKILL')]}), ('Graph Theory', {'entities': [(0, 12, 'SKILL')]}), ('Dynamic Programming', {'entities': [(0, 19, 'SKILL')]}), ('Agile', {'entities': [(0, 5, 'SKILL')]}), ('Scrum', {'entities': [(0, 5, 'SKILL')]}), ('Kanban', {'entities': [(0, 6, 'SKILL')]}), ('Object-Oriented Programming (OOP)', {'entities': [(0, 33, 'SKILL')]}), ('Functional Programming', {'entities': [(0, 22, 'SKILL')]}), ('Event-Driven Programming', {'entities': [(0, 24, 'SKILL')]}), ('WebSockets', {'entities': [(0, 10, 'SKILL')]}), ('GraphQL', {'entities': [(0, 7, 'SKILL')]}), ('WebAssembly', {'entities': [(0, 11, 'SKILL')]}), ('Apache', {'entities': [(0, 6, 'SKILL')]}), ('Nginx', {'entities': [(0, 5, 'SKILL')]}), ('Tomcat', {'entities': [(0, 6, 'SKILL')]}), ('JUnit', {'entities': [(0, 5, 'SKILL')]}), ('Selenium', {'entities': [(0, 8, 'SKILL')]}), ('Jest', {'entities': [(0, 4, 'SKILL')]}), ('Continuous Integration', {'entities': [(0, 22, 'SKILL')]}), ('Continuous Deployment', {'entities': [(0, 21, 'SKILL')]}), ('OpenAPI', {'entities': [(0, 7, 'SKILL')]}), ('Postman', {'entities': [(0, 7, 'SKILL')]}), ('TCP/IP', {'entities': [(0, 6, 'SKILL')]}), ('DNS', {'entities': [(0, 3, 'SKILL')]}), ('HTTP/HTTPS', {'entities': [(0, 10, 'SKILL')]}), ('VPN', {'entities': [(0, 3, 'SKILL')]}), ('Spring (Java)', {'entities': [(0, 13, 'SKILL')]}), ('Django (Python)', {'entities': [(0, 15, 'SKILL')]}), ('Ruby on Rails', {'entities': [(0, 13, 'SKILL')]}), ('Flask (Python)', {'entities': [(0, 14, 'SKILL')]}), ('Visual Studio Code', {'entities': [(0, 18, 'SKILL')]}), ('IntelliJ IDEA', {'entities': [(0, 13, 'SKILL')]}), ('Eclipse', {'entities': [(0, 7, 'SKILL')]}), ('Jira', {'entities': [(0, 4, 'SKILL')]}), ('Trello', {'entities': [(0, 6, 'SKILL')]}), ('Asana', {'entities': [(0, 5, 'SKILL')]}), ('Communication', {'entities': [(0, 13, 'SKILL')]}), ('Problem-Solving', {'entities': [(0, 15, 'SKILL')]}), ('Team Collaboration', {'entities': [(0, 18, 'SKILL')]}), ('Time Management', {'entities': [(0, 15, 'SKILL')]}), ('Adaptability', {'entities': [(0, 12, 'SKILL')]}), ('Shell scripting', {'entities': [(0, 15, 'SKILL')]}), ('D3.js (Data-Driven Documents)', {'entities': [(0, 29, 'SKILL')]}), ('Redux (State management for JavaScript apps)', {'entities': [(0, 44, 'SKILL')]}), ('Xamarin (Cross-platform mobile app development)', {'entities': [(0, 47, 'SKILL')]}), ('Flask-RESTful (RESTful API development in Python)', {'entities': [(0, 49, 'SKILL')]}), ('BigQuery (Google Cloud data warehouse)', {'entities': [(0, 38, 'SKILL')]}), ('Hadoop', {'entities': [(0, 6, 'SKILL')]}), ('MapReduce', {'entities': [(0, 9, 'SKILL')]}), ('Apache Kafka (Distributed streaming platform)', {'entities': [(0, 45, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('GraphQL (Query language for APIs)', {'entities': [(0, 33, 'SKILL')]}), ('Redux-Saga (Middleware library for Redux)', {'entities': [(0, 41, 'SKILL')]}), ('Electron (Cross-platform desktop app development)', {'entities': [(0, 49, 'SKILL')]}), ('Polymer (JavaScript library for building web components)', {'entities': [(0, 56, 'SKILL')]}), ('Rust (Programming language focused on performance and safety)', {'entities': [(0, 61, 'SKILL')]}), ('Clojure (Functional programming language)', {'entities': [(0, 41, 'SKILL')]}), ('Elm (Functional programming language for front-end development)', {'entities': [(0, 63, 'SKILL')]}), ('Meteor (Full-stack JavaScript framework)', {'entities': [(0, 40, 'SKILL')]}), ('Apache Spark (Distributed computing)', {'entities': [(0, 36, 'SKILL')]}), ('RxJS (Reactive programming in JavaScript)', {'entities': [(0, 41, 'SKILL')]}), ('Blockchain development', {'entities': [(0, 22, 'SKILL')]}), ('Solidity (Programming language for smart contracts)', {'entities': [(0, 51, 'SKILL')]}), ('Apache Cordova (Mobile app development using web technologies)', {'entities': [(0, 62, 'SKILL')]}), ('Flask-SQLAlchemy (SQL toolkit for Python)', {'entities': [(0, 41, 'SKILL')]}), ('GraphQL Yoga (Fully-featured GraphQL server)', {'entities': [(0, 44, 'SKILL')]}), ('Firebase (Mobile and web application development platform)', {'entities': [(0, 58, 'SKILL')]}), ('Amazon DynamoDB (NoSQL database)', {'entities': [(0, 32, 'SKILL')]}), ('Apache Cassandra (Distributed NoSQL database)', {'entities': [(0, 45, 'SKILL')]}), ('Neo4j (Graph database)', {'entities': [(0, 22, 'SKILL')]}), ('Microsoft SQL Server', {'entities': [(0, 20, 'SKILL')]}), ('Heroku (Cloud platform as a service)', {'entities': [(0, 36, 'SKILL')]}), ('PaaS (Platform as a Service)', {'entities': [(0, 28, 'SKILL')]}), ('Serverless architecture', {'entities': [(0, 23, 'SKILL')]}), ('Microservices architecture', {'entities': [(0, 26, 'SKILL')]}), ('Istio (Service mesh)', {'entities': [(0, 20, 'SKILL')]}), ('AWS Lambda (Serverless computing)', {'entities': [(0, 33, 'SKILL')]}), ('Jupyter Notebooks (Interactive computing and data visualization)', {'entities': [(0, 64, 'SKILL')]}), ('R programming language', {'entities': [(0, 22, 'SKILL')]}), ('Julia (Programming language for technical computing)', {'entities': [(0, 52, 'SKILL')]}), ('Grafana (Open-source analytics and monitoring platform)', {'entities': [(0, 55, 'SKILL')]}), ('Prometheus (Monitoring and alerting toolkit)', {'entities': [(0, 44, 'SKILL')]}), ('Splunk (Data analysis and visualization)', {'entities': [(0, 40, 'SKILL')]}), ('Kibana (Data visualization tool)', {'entities': [(0, 32, 'SKILL')]}), ('Grafana (Open-source analytics and monitoring platform)', {'entities': [(0, 55, 'SKILL')]}), ('Zeppelin (Web-based notebook for data analytics)', {'entities': [(0, 48, 'SKILL')]}), ('Data warehousing', {'entities': [(0, 16, 'SKILL')]}), ('Power BI (Business analytics tool)', {'entities': [(0, 34, 'SKILL')]}), ('Tableau (Data visualization and business intelligence)', {'entities': [(0, 54, 'SKILL')]}), ('Snowflake (Cloud-based data warehousing)', {'entities': [(0, 40, 'SKILL')]}), ('Augmented Reality (AR)', {'entities': [(0, 22, 'SKILL')]}), ('Virtual Reality (VR)', {'entities': [(0, 20, 'SKILL')]}), ('Computer vision', {'entities': [(0, 15, 'SKILL')]}), ('Natural Language Generation (NLG)', {'entities': [(0, 33, 'SKILL')]}), ('Automated Speech Recognition (ASR)', {'entities': [(0, 34, 'SKILL')]}), ('Computer-aided design (CAD)', {'entities': [(0, 27, 'SKILL')]}), ('Cyber-physical systems', {'entities': [(0, 22, 'SKILL')]}), ('Quantum computing', {'entities': [(0, 17, 'SKILL')]}), ('Web scraping', {'entities': [(0, 12, 'SKILL')]}), ('RESTful design principles', {'entities': [(0, 25, 'SKILL')]}), ('GraphQL mutations', {'entities': [(0, 17, 'SKILL')]}), ('OAuth (Authorization framework)', {'entities': [(0, 31, 'SKILL')]}), ('OpenID Connect (Authentication on top of OAuth)', {'entities': [(0, 47, 'SKILL')]}), ('JSON Web Tokens (JWT)', {'entities': [(0, 21, 'SKILL')]}), ('OAuth2.0', {'entities': [(0, 8, 'SKILL')]}), ('OpenID Connect (OIDC)', {'entities': [(0, 21, 'SKILL')]}), ('WebAuthn (Web Authentication API)', {'entities': [(0, 33, 'SKILL')]}), ('JWT (JSON Web Tokens)', {'entities': [(0, 21, 'SKILL')]}), ('OAuth (Open Authorization)', {'entities': [(0, 26, 'SKILL')]}), ('OAuth2.0 (Authorization framework)', {'entities': [(0, 34, 'SKILL')]}), ('OpenID Connect (Authentication on top of OAuth)', {'entities': [(0, 47, 'SKILL')]}), ('Firebase Authentication', {'entities': [(0, 23, 'SKILL')]}), ('Single Sign-On (SSO)', {'entities': [(0, 20, 'SKILL')]}), ('Two-Factor Authentication (2FA)', {'entities': [(0, 31, 'SKILL')]}), ('FIDO2 (WebAuthn)', {'entities': [(0, 16, 'SKILL')]}), ('Identity and Access Management (IAM)', {'entities': [(0, 36, 'SKILL')]}), ('RBAC (Role-Based Access Control)', {'entities': [(0, 32, 'SKILL')]}), ('ABAC (Attribute-Based Access Control)', {'entities': [(0, 37, 'SKILL')]}), ('CQRS (Command Query Responsibility Segregation)', {'entities': [(0, 47, 'SKILL')]}), ('Event Sourcing', {'entities': [(0, 14, 'SKILL')]}), ('Micro Frontends', {'entities': [(0, 15, 'SKILL')]}), ('Progressive Web Apps (PWAs)', {'entities': [(0, 27, 'SKILL')]}), ('Single Page Applications (SPAs)', {'entities': [(0, 31, 'SKILL')]}), ('WebAssembly (Wasm)', {'entities': [(0, 18, 'SKILL')]}), ('OpenAPI Specification', {'entities': [(0, 21, 'SKILL')]}), ('SOAP (Simple Object Access Protocol)', {'entities': [(0, 36, 'SKILL')]}), ('GraphQL subscriptions', {'entities': [(0, 21, 'SKILL')]}), ('Server-Sent Events (SSE)', {'entities': [(0, 24, 'SKILL')]}), ('WebSockets', {'entities': [(0, 10, 'SKILL')]}), ('Webhooks', {'entities': [(0, 8, 'SKILL')]}), ('Application Performance Monitoring (APM)', {'entities': [(0, 40, 'SKILL')]}), ('Log management', {'entities': [(0, 14, 'SKILL')]}), ('Error tracking', {'entities': [(0, 14, 'SKILL')]}), ('Distributed tracing', {'entities': [(0, 19, 'SKILL')]}), ('Chaos engineering', {'entities': [(0, 17, 'SKILL')]}), ('Load balancing', {'entities': [(0, 14, 'SKILL')]}), ('Critical Thinking', {'entities': [(0, 17, 'SKILL')]}), ('Problem-Solving', {'entities': [(0, 15, 'SKILL')]}), ('Decision Making', {'entities': [(0, 15, 'SKILL')]}), ('Analytical Skills', {'entities': [(0, 17, 'SKILL')]}), ('Creativity', {'entities': [(0, 10, 'SKILL')]}), ('Innovation', {'entities': [(0, 10, 'SKILL')]}), ('Adaptability', {'entities': [(0, 12, 'SKILL')]}), ('Time Management', {'entities': [(0, 15, 'SKILL')]}), ('Organization', {'entities': [(0, 12, 'SKILL')]}), ('Prioritization', {'entities': [(0, 14, 'SKILL')]}), ('Communication', {'entities': [(0, 13, 'SKILL')]}), ('Collaboration', {'entities': [(0, 13, 'SKILL')]}), ('Teamwork', {'entities': [(0, 8, 'SKILL')]}), ('Leadership', {'entities': [(0, 10, 'SKILL')]}), ('Conflict Resolution', {'entities': [(0, 19, 'SKILL')]}), ('Emotional Intelligence', {'entities': [(0, 22, 'SKILL')]}), ('Empathy', {'entities': [(0, 7, 'SKILL')]}), ('Active Listening', {'entities': [(0, 16, 'SKILL')]}), ('Presentation Skills', {'entities': [(0, 19, 'SKILL')]}), ('Public Speaking', {'entities': [(0, 15, 'SKILL')]}), ('Negotiation', {'entities': [(0, 11, 'SKILL')]}), ('Networking', {'entities': [(0, 10, 'SKILL')]}), ('Customer Service', {'entities': [(0, 16, 'SKILL')]}), ('Client Management', {'entities': [(0, 17, 'SKILL')]}), ('Relationship Building', {'entities': [(0, 21, 'SKILL')]}), ('Cultural Sensitivity', {'entities': [(0, 20, 'SKILL')]}), ('Ethics', {'entities': [(0, 6, 'SKILL')]}), ('Integrity', {'entities': [(0, 9, 'SKILL')]}), ('Initiative', {'entities': [(0, 10, 'SKILL')]}), ('Self-Motivation', {'entities': [(0, 15, 'SKILL')]}), ('Learning Agility', {'entities': [(0, 16, 'SKILL')]}), ('Flexibility', {'entities': [(0, 11, 'SKILL')]}), ('Resilience', {'entities': [(0, 10, 'SKILL')]}), ('Stress Management', {'entities': [(0, 17, 'SKILL')]}), ('Interpersonal Skills', {'entities': [(0, 20, 'SKILL')]}), ('Cross-Cultural Competence', {'entities': [(0, 25, 'SKILL')]}), ('Business Acumen', {'entities': [(0, 15, 'SKILL')]}), ('Project Management', {'entities': [(0, 18, 'SKILL')]}), ('Risk Management', {'entities': [(0, 15, 'SKILL')]}), ('Quality Assurance', {'entities': [(0, 17, 'SKILL')]}), ('Conflict Management', {'entities': [(0, 19, 'SKILL')]}), ('Change Management', {'entities': [(0, 17, 'SKILL')]}), ('Decision-Making', {'entities': [(0, 15, 'SKILL')]}), ('Financial Literacy', {'entities': [(0, 18, 'SKILL')]}), ('Entrepreneurship', {'entities': [(0, 16, 'SKILL')]}), ('Business Development', {'entities': [(0, 20, 'SKILL')]}), ('Sales Skills', {'entities': [(0, 12, 'SKILL')]}), ('Marketing', {'entities': [(0, 9, 'SKILL')]}), ('Customer Relationship Management (CRM)', {'entities': [(0, 38, 'SKILL')]}), ('Strategic Planning', {'entities': [(0, 18, 'SKILL')]}), ('Data Literacy', {'entities': [(0, 13, 'SKILL')]}), ('Digital Literacy', {'entities': [(0, 16, 'SKILL')]}), ('Information Literacy', {'entities': [(0, 20, 'SKILL')]}), ('Research Skills', {'entities': [(0, 15, 'SKILL')]}), ('Technical Writing', {'entities': [(0, 17, 'SKILL')]}), ('Documentation', {'entities': [(0, 13, 'SKILL')]}), ('Report Writing', {'entities': [(0, 14, 'SKILL')]}), ('Blogging', {'entities': [(0, 8, 'SKILL')]}), ('Public Relations', {'entities': [(0, 16, 'SKILL')]}), ('Time Tracking', {'entities': [(0, 13, 'SKILL')]}), ('Goal Setting', {'entities': [(0, 12, 'SKILL')]}), ('Delegation', {'entities': [(0, 10, 'SKILL')]}), ('Motivational Skills', {'entities': [(0, 19, 'SKILL')]}), ('Cross-Functional Collaboration', {'entities': [(0, 30, 'SKILL')]}), ('Stakeholder Management', {'entities': [(0, 22, 'SKILL')]}), ('Feedback and Coaching', {'entities': [(0, 21, 'SKILL')]}), ('Mentoring', {'entities': [(0, 9, 'SKILL')]}), ('Knowledge Sharing', {'entities': [(0, 17, 'SKILL')]}), ('Training and Development', {'entities': [(0, 24, 'SKILL')]}), ('Conflict Resolution', {'entities': [(0, 19, 'SKILL')]}), ('Facilitation Skills', {'entities': [(0, 19, 'SKILL')]}), ('Decision Making Under Pressure', {'entities': [(0, 30, 'SKILL')]}), ('Attention to Detail', {'entities': [(0, 19, 'SKILL')]}), ('Project Coordination', {'entities': [(0, 20, 'SKILL')]}), ('Crisis Management', {'entities': [(0, 17, 'SKILL')]}), ('Strategic Thinking', {'entities': [(0, 18, 'SKILL')]}), ('Systems Thinking', {'entities': [(0, 16, 'SKILL')]}), ('Forecasting', {'entities': [(0, 11, 'SKILL')]}), ('Trend Analysis', {'entities': [(0, 14, 'SKILL')]}), ('Presentation Design', {'entities': [(0, 19, 'SKILL')]}), ('Data Visualization', {'entities': [(0, 18, 'SKILL')]}), ('Storytelling', {'entities': [(0, 12, 'SKILL')]}), ('Cultural Intelligence', {'entities': [(0, 21, 'SKILL')]}), ('Social Media Management', {'entities': [(0, 23, 'SKILL')]}), ('Community Building', {'entities': [(0, 18, 'SKILL')]}), ('Volunteerism', {'entities': [(0, 12, 'SKILL')]}), ('Time Blocking', {'entities': [(0, 13, 'SKILL')]}), ('Goal Setting', {'entities': [(0, 12, 'SKILL')]}), ('Continuous Improvement', {'entities': [(0, 22, 'SKILL')]}), ('Team Building', {'entities': [(0, 13, 'SKILL')]}), ('Appreciative Inquiry', {'entities': [(0, 20, 'SKILL')]}), ('User-Centered Design', {'entities': [(0, 20, 'SKILL')]}), ('User Experience (UX) Design', {'entities': [(0, 27, 'SKILL')]}), ('User Interface (UI) Design', {'entities': [(0, 26, 'SKILL')]}), ('Human-Computer Interaction (HCI)', {'entities': [(0, 32, 'SKILL')]}), ('Design Thinking', {'entities': [(0, 15, 'SKILL')]}), ('Agile Methodology', {'entities': [(0, 17, 'SKILL')]}), ('Scrum', {'entities': [(0, 5, 'SKILL')]}), ('Kanban', {'entities': [(0, 6, 'SKILL')]}), ('Lean Thinking', {'entities': [(0, 13, 'SKILL')]}), ('Racket (Lisp dialect)', {'entities': [(0, 21, 'SKILL')]}), ('Julia (Programming language for technical computing)', {'entities': [(0, 52, 'SKILL')]}), ('Shell scripting', {'entities': [(0, 15, 'SKILL')]}), ('WebRTC (Real-Time Communication)', {'entities': [(0, 32, 'SKILL')]}), ('NATS (Messaging system)', {'entities': [(0, 23, 'SKILL')]}), ('CockroachDB (Distributed SQL database)', {'entities': [(0, 38, 'SKILL')]}), ('InfluxDB (Open-source time-series database)', {'entities': [(0, 43, 'SKILL')]}), ('ArangoDB (Multi-model NoSQL database)', {'entities': [(0, 37, 'SKILL')]}), ('Flink (Stream processing framework)', {'entities': [(0, 35, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('Celery (Distributed task queue)', {'entities': [(0, 31, 'SKILL')]}), ('Redis (In-memory data structure store)', {'entities': [(0, 38, 'SKILL')]}), ('GraphQL subscriptions', {'entities': [(0, 21, 'SKILL')]}), ('GRPC (Remote procedure call framework)', {'entities': [(0, 38, 'SKILL')]}), ('Protocol Buffers', {'entities': [(0, 16, 'SKILL')]}), ('Flutter (UI toolkit for building natively compiled applications)', {'entities': [(0, 64, 'SKILL')]}), ('Xamarin (Cross-platform mobile app development)', {'entities': [(0, 47, 'SKILL')]}), ('Unity (Game development)', {'entities': [(0, 24, 'SKILL')]}), ('Godot Engine (Open-source game development)', {'entities': [(0, 43, 'SKILL')]}), ('Rust (Programming language focused on performance and safety)', {'entities': [(0, 61, 'SKILL')]}), ('ClojureScript (Clojure compiler for JavaScript)', {'entities': [(0, 47, 'SKILL')]}), ('Elm (Functional programming language for front-end development)', {'entities': [(0, 63, 'SKILL')]}), ('Meteor (Full-stack JavaScript framework)', {'entities': [(0, 40, 'SKILL')]}), ('Puppet (Configuration management tool)', {'entities': [(0, 38, 'SKILL')]}), ('Chef (Infrastructure automation framework)', {'entities': [(0, 42, 'SKILL')]}), ('Pulumi (Infrastructure as code)', {'entities': [(0, 31, 'SKILL')]}), ('HashiCorp Vault (Secrets management)', {'entities': [(0, 36, 'SKILL')]}), ('Cockpit (Linux server management)', {'entities': [(0, 33, 'SKILL')]}), ('Apache Kafka Streams (Stream processing library)', {'entities': [(0, 48, 'SKILL')]}), ('Logstash (Server-side data processing pipeline)', {'entities': [(0, 47, 'SKILL')]}), ('Kibana (Data visualization tool)', {'entities': [(0, 32, 'SKILL')]}), ('RabbitMQ (Message broker)', {'entities': [(0, 25, 'SKILL')]}), ('NATS (Messaging system)', {'entities': [(0, 23, 'SKILL')]}), ('Fluentd (Open-source data collector)', {'entities': [(0, 36, 'SKILL')]}), ('ArgoCD (GitOps continuous delivery tool

In [9]:
#print("عدد العناصر في TRAIN_DATA:", len(TRAIN_DATA))

عدد العناصر في TRAIN_DATA: 876

In [14]:
TRAIN_DATA = [
    ("Proficient in Python, Java, and C++", {"entities": [(13, 19, "SKILL"), (21, 25, "SKILL"), (30, 33, "SKILL")]}),
    ("Experience with machine learning algorithms", {"entities": [(12, 28, "SKILL")]}),
    ("Familiar with TensorFlow and PyTorch", {"entities": [(13, 24, "SKILL"), (29, 36, "SKILL")]}),
    ("Strong understanding of HTML, CSS, and JavaScript", {"entities": [(19, 22, "SKILL"), (24, 27, "SKILL"), (32, 41, "SKILL")]}),
    ("Expertise in data analysis and visualization using Tableau", {"entities": [(20, 30, "SKILL"), (35, 46, "SKILL")]}),
    ("Skilled in SQL database management", {"entities": [(10, 13, "SKILL"), (24, 35, "SKILL")]}),
    ("Knowledge of React and Angular frameworks", {"entities": [(12, 17, "SKILL"), (22, 29, "SKILL")]}),
    ("Proficiency in MATLAB for numerical computing", {"entities": [(14, 19, "SKILL"), (28, 44, "SKILL")]}),
    ("Experience with cloud technologies like AWS and Azure", {"entities": [(17, 20, "SKILL"), (25, 30, "SKILL")]}),
    ("Expertise in natural language processing and NLP techniques", {"entities": [(20, 46, "SKILL"), (51, 54, "SKILL")]}),
    ("Familiarity with Git version control system", {"entities": [(16, 18, "SKILL"), (30, 36, "SKILL")]}),
    ("Knowledgeable in DevOps practices and CI/CD pipelines", {"entities": [(14, 20, "SKILL"), (37, 41, "SKILL")]}),
    ("Proficient in Java Spring and Hibernate frameworks", {"entities": [(14, 24, "SKILL"), (29, 38, "SKILL")]}),
    ("Expert in Linux kernel and system administration", {"entities": [(5, 10, "SKILL"), (17, 26, "SKILL"), (33, 53, "SKILL")]}),
    ("Advanced networking skills - configuring routers, switches, firewalls", {"entities": [(8, 22, "SKILL"), (25, 41, "SKILL"), (44, 54, "SKILL"), (57, 66, "SKILL")]}),
    ("Experience setting up Kubernetes clusters on AWS and GCP", {"entities": [(17, 28, "SKILL"), (37, 57, "SKILL"), (61, 64, "SKILL")]}),
    ("Skilled software developer with 5 years building scalable web apps", {"entities": [(10, 26, "SKILL"), (52, 68, "SKILL"), (73, 83, "SKILL")]}),
    ("Proficiency in Java, Python, C++, JavaScript, and Golang", {"entities": [(14, 19, "SKILL"), (22, 28, "SKILL"), (31, 34, "SKILL"), (37, 47, "SKILL"), (52, 58, "SKILL")]}),
    ("Expertise in full stack development using MongoDB, Express, React, Node", {"entities": [(20, 33, "SKILL"), (44, 51, "SKILL"), (55, 61, "SKILL"), (65, 70, "SKILL"), (74, 78, "SKILL")]}),
    ("Experience with machine learning libraries PyTorch, TensorFlow, Keras", {"entities": [(17, 45, "SKILL"), (50, 60, "SKILL"), (65, 75, "SKILL"), (80, 85, "SKILL")]}),
    ("Skilled in CI/CD pipelines, GitLab, Jenkins, Bamboo, CircleCI", {"entities": [[10, 24, "SKILL"], [29, 35, "SKILL"], [40, 47, "SKILL"], [52, 59, "SKILL"], [64, 72, "SKILL"]]}),
    # Additional examples with skill-related keywords
    ("SQL", {"entities": [(0, 3, "SKILL")]}),
    ("JavaScript", {"entities": [(0, 10, "SKILL")]}),
    ("Machine Learning", {"entities": [(0, 16, "SKILL")]}),
    ("Data Analysis", {"entities": [(0, 13, "SKILL")]}),
    ("React.js", {"entities": [(0, 8, "SKILL")]}),
    ("AngularJS", {"entities": [(0, 9, "SKILL")]}),
    ("Node.js", {"entities": [(0, 7, "SKILL")]}),
    ("MongoDB", {"entities": [(0, 7, "SKILL")]}),
    ("AWS Cloud", {"entities": [(0, 8, "SKILL")]}),
    ("Azure Cloud", {"entities": [(0, 11, "SKILL")]}),
    ("Statistical Modeling", {"entities": [(0, 20, "SKILL")]}),
    ("Linux operating system", {"entities": [(0, 5, "SKILL")]}),
    ("Windows Server administration", {"entities": [(0, 6, "SKILL"), (17, 28, "SKILL")]}),
    ("Network configuration and troubleshooting", {"entities": [(0, 8, "SKILL"), (25, 42, "SKILL")]}),
    ("TCP/IP, OSI model", {"entities": [(0, 7, "SKILL"), (12, 17, "SKILL")]}),
    ("Routing protocols like OSPF, BGP", {"entities": [(0, 15, "SKILL"), (22, 25, "SKILL"), (30, 33, "SKILL")]}),
    ("Cisco switching and routing", {"entities": [(0, 5, "SKILL"), (13, 19, "SKILL")]}),
    ("VPN configuration", {"entities": [(0, 13, "SKILL")]}),
    ("Firewall administration", {"entities": [(0, 9, "SKILL"), (17, 28, "SKILL")]}),
    ("Network security", {"entities": [(0, 14, "SKILL")]}),
    ("Penetration testing", {"entities": [(0, 19, "SKILL")]}),
    ("Burp Suite", {"entities": [(0, 9, "SKILL")]}),
    ("Wireshark network analysis", {"entities": [(0, 9, "SKILL"), (17, 32, "SKILL")]}),
    ("CCNA certification", {"entities": [(0, 10, "SKILL")]}),
    ("VMware administration", {"entities": [(0, 6, "SKILL"), (17, 28, "SKILL")]}),
    ("SAN storage configuration", {"entities": [(0, 3, "SKILL"), (14, 32, "SKILL")]}),
    ("NAS storage administration", {"entities": [(0, 3, "SKILL"), (15, 33, "SKILL")]}),
    ("RAID arrays", {"entities": [(0, 7, "SKILL")]}),
    ("Docker containerization", {"entities": [(0, 6, "SKILL"), (17, 32, "SKILL")]}),
    ("Kubernetes", {"entities": [(0, 10, "SKILL")]}),
    ("Jenkins CI/CD pipelines", {"entities": [(0, 7, "SKILL"), (17, 30, "SKILL")]}),
    ("Ansible automation", {"entities": [(0, 6, "SKILL"), (17, 27, "SKILL")]}),
    ("Terraform infrastructure-as-code", {"entities": [(0, 9, "SKILL"), (18, 38, "SKILL")]}),
    ("Azure administration", {"entities": [(0, 6, "SKILL"), (17, 29, "SKILL")]}),
    ("AWS cloud architecture", {"entities": [(0, 3, "SKILL"), (13, 29, "SKILL")]}),
    ("Google Cloud Platform", {"entities": [(0, 22, "SKILL")]}),
    ("DevOps culture and practices ", {"entities": [(0, 6, "SKILL"), (18, 34, "SKILL")]}),
    ("Agile development methodologies", {"entities": [(0, 5, "SKILL"), (20, 42, "SKILL")]}),
    ("Waterfall SDLC", {"entities": [(0, 8, "SKILL"), (13, 16, "SKILL")]}),
    ("Object-oriented analysis and design", {"entities": [(0, 25, "SKILL"), (31, 36, "SKILL")]}),
    ("SQL database programming", {"entities": [(0, 3, "SKILL"), (14, 28, "SKILL")]}),
    ("Oracle database administration", {"entities": [(0, 6, "SKILL"), (17, 35, "SKILL")]}),
    ("MongoDB NoSQL databases", {"entities": [(0, 7, "SKILL"), (15, 29, "SKILL")]}),
    ("Redis in-memory caching", {"entities": [(0, 5, "SKILL"), (17, 29, "SKILL")]}),
    ("Data modeling and warehousing", {"entities": [(0, 15, "SKILL"), (21, 32, "SKILL")]}),
    ("ETL processing pipelines", {"entities": [(0, 3, "SKILL"), (15, 31, "SKILL")]}),
    ("Hadoop cluster configuration", {"entities": [(0, 6, "SKILL"), (20, 38, "SKILL")]}),
    ("Spark big data processing", {"entities": [(0, 5, "SKILL"), (16, 30, "SKILL")]}),
    ("Tableau data visualization", {"entities": [(0, 7, "SKILL"), (17, 33, "SKILL")]}),
    ("Power BI business analytics", {"entities": [(0, 8, "SKILL"), (17, 33, "SKILL")]}),
    ("Python programming", {"entities": [(0, 6, "SKILL"), (17, 28, "SKILL")]}),
    ("Java Spring Boot framework", {"entities": [(0, 4, "SKILL"), (10, 26, "SKILL")]}),
    ("PHP web application development", {"entities": [(0, 3, "SKILL"), (14, 37, "SKILL")]}),
    ("Ruby on Rails web framework", {"entities": [(0, 3, "SKILL"), (10, 27, "SKILL")]}),
    ("JavaScript front-end development", {"entities": [(0, 10, "SKILL"), (22, 40, "SKILL")]}),
    ("React web applications", {"entities": [(0, 5, "SKILL"), (16, 30, "SKILL")]}),
    ("Angular single page applications", {"entities": [(0, 7, "SKILL"), (17, 37, "SKILL")]}),
    ("Node.js back-end services", {"entities": [(0, 7, "SKILL"), (17, 29, "SKILL")]}),
    ("REST API design and development", {"entities": [(0, 10, "SKILL"), (28, 47, "SKILL")]}),
    ("GraphQL API development", {"entities": [(0, 7, "SKILL"), (17, 31, "SKILL")]}),
    ("Unit testing frameworks like JUnit", {"entities": [(0, 15, "SKILL"), (24, 29, "SKILL")]}),
    ("UX design and usability", {"entities": [(0, 7, "SKILL"), (16, 27, "SKILL")]}),
    ("Git version control system", {"entities": [(0, 18, "SKILL"), (30, 36, "SKILL")]}),
    ("Continuous integration and delivery", {"entities": [(0, 28, "SKILL"), (36, 44, "SKILL")]}),
    ("R language data analysis", {"entities": [(0, 11, "SKILL"), (20, 33, "SKILL")]}),
    ("MATLAB numerical computing", {"entities": [(0, 6, "SKILL"), (17, 31, "SKILL")]}),
    ("C++ high performance programming", {"entities": [(0, 2, "SKILL"), (18, 37, "SKILL")]}),
    ("Multithreading and concurrency", {"entities": [(0, 15, "SKILL"), (22, 34, "SKILL")]}),
    ("Cryptography and encryption algorithms", {"entities": [(0, 13, "SKILL"), (24, 44, "SKILL")]}),
    ("Cybersecurity awareness ", {"entities": [(0, 14, "SKILL"), (26, 40, "SKILL")]}),
    ("Penetration testing and ethical hacking", {"entities": [(0, 23, "SKILL"), (31, 47, "SKILL")]}),
    ("Artificial intelligence and machine learning", {"entities": [(0, 25, "SKILL"), (35, 52, "SKILL")]}),
    ("Neural networks and deep learning", {"entities": [(0, 15, "SKILL"), (25, 39, "SKILL")]}),
    ("Computer vision with OpenCV", {"entities": [(0, 16, "SKILL"), (26, 32, "SKILL")]}),
    ("Natural language processing techniques", {"entities": [(0, 33, "SKILL"), (46, 58, "SKILL")]}),
    ("Recommender systems algorithms", {"entities": [(0, 23, "SKILL"), (30, 42, "SKILL")]}),
    ("Python", {"entities": [(0, 6, "SKILL")]}),
    ("Java", {"entities": [(0, 4, "SKILL")]}),
    ("JavaScript", {"entities": [(0, 10, "SKILL")]}),
    ("TypeScript", {"entities": [(0, 10, "SKILL")]}),
    ("C++", {"entities": [(0, 3, "SKILL")]}),
    ("C#", {"entities": [(0, 2, "SKILL")]}),
    ("Go", {"entities": [(0, 2, "SKILL")]}),
    ("Ruby", {"entities": [(0, 4, "SKILL")]}),
    ("PHP", {"entities": [(0, 3, "SKILL")]}),
    ("Swift", {"entities": [(0, 5, "SKILL")]}),
    ("Rust", {"entities": [(0, 4, "SKILL")]}),
    ("Dart", {"entities": [(0, 4, "SKILL")]}),
    ("Kotlin", {"entities": [(0, 6, "SKILL")]}),
    ("SQL", {"entities": [(0, 3, "SKILL")]}),
    ("NoSQL", {"entities": [(0, 5, "SKILL")]}),
    ("C", {"entities": [(0, 1, "SKILL")]}),
    ("Scala", {"entities": [(0, 5, "SKILL")]}),
    ("Perl", {"entities": [(0, 4, "SKILL")]}),
    ("Haskell", {"entities": [(0, 7, "SKILL")]}),
    ("Bash", {"entities": [(0, 4, "SKILL")]}),
    ("Shell", {"entities": [(0, 5, "SKILL")]}),
    ("Cobol", {"entities": [(0,5, "SKILL")]}),
    ("Fortran", {"entities": [(0,7, "SKILL")]}),
    ("Visual Basic", {"entities": [(0,13, "SKILL")]}),
    ("Assembly", {"entities": [(0,9, "SKILL")]}),
    ("Pascal", {"entities": [(0,6, "SKILL")]}),
    ("Ada", {"entities": [(0,3, "SKILL")]}),
    ("ABAP", {"entities": [(0,4, "SKILL")]}),
    ("RPG", {"entities": [(0,3, "SKILL")]}),
    ("Lisp", {"entities": [(0,4, "SKILL")]}),
    ("Prolog", {"entities": [(0,6, "SKILL")]}),
    ("F#", {"entities": [(0,2, "SKILL")]}),
    ("Lua", {"entities": [(0,3, "SKILL")]}),
    ("MATLAB", {"entities": [(0,6, "SKILL")]}),
    ("SAS", {"entities": [(0,3, "SKILL")]}),
    ("SPSS", {"entities": [(0,4, "SKILL")]}),
    ("R", {"entities": [(0,1, "SKILL")]}),
    ("Julia", {"entities": [(0,5, "SKILL")]}),
    ("Mahout", {"entities": [(0,6, "SKILL")]}),
    ("Solr", {"entities": [(0,4, "SKILL")]}),
    ("Lucene", {"entities": [(0,6, "SKILL")]}),
    ("HBase", {"entities": [(0,4, "SKILL")]}),
    ("Cassandra", {"entities": [(0,9, "SKILL")]}),
    ("Neo4j", {"entities": [(0,5, "SKILL")]}),
    ("Unix", {"entities": [(0,4, "SKILL")]}),
    ("Linux", {"entities": [(0,5, "SKILL")]}),
    ("Windows", {"entities": [(0,7, "SKILL")]}),
    ("MacOS", {"entities": [(0,5, "SKILL")]}),
    ("Android", {"entities": [(0,7, "SKILL")]}),
]

In [15]:
import spacy
from spacy.training.example import Example
import random
import os

output_dir = "skills_ner_model"

nlp = spacy.blank("en")

ner = nlp.add_pipe("ner", name="ner", last=True)
ner.add_label("SKILL")

nlp.begin_training()

iterations = 30

for itn in range(iterations):
    random.shuffle(TRAIN_DATA)
    losses = {}
    for text, annotations in TRAIN_DATA:
        doc = nlp.make_doc(text)
        example = Example.from_dict(doc, annotations)
        nlp.update([example], drop=0.5, losses=losses)

    print(f"Iteration {itn+1}: Loss = {losses}")

os.makedirs(output_dir, exist_ok=True)

nlp.to_disk(output_dir)
print(f"✅ تم حفظ النموذج في: {output_dir}")

Iteration 1: Loss = {'ner': 135.14835905116888}
Iteration 2: Loss = {'ner': 87.7743106276094}
Iteration 3: Loss = {'ner': 64.81966303164663}
Iteration 4: Loss = {'ner': 49.89482910645295}
Iteration 5: Loss = {'ner': 30.550571340094884}
Iteration 6: Loss = {'ner': 38.0048764252237}
Iteration 7: Loss = {'ner': 27.90509147585305}
Iteration 8: Loss = {'ner': 36.58485835324874}
Iteration 9: Loss = {'ner': 32.97480456075448}
Iteration 10: Loss = {'ner': 24.90337728364736}
Iteration 11: Loss = {'ner': 19.99142704844881}
Iteration 12: Loss = {'ner': 14.304584054095425}
Iteration 13: Loss = {'ner': 7.68698325949315}
Iteration 14: Loss = {'ner': 16.286553904681757}
Iteration 15: Loss = {'ner': 22.922193703036648}
Iteration 16: Loss = {'ner': 8.595455207180535}
Iteration 17: Loss = {'ner': 10.185789277888105}
Iteration 18: Loss = {'ner': 16.151687705181047}
Iteration 19: Loss = {'ner': 15.0899487583264}
Iteration 20: Loss = {'ner': 14.487046010212865}
Iteration 21: Loss = {'ner': 10.68329230004801}
Iteration 22: Loss = {'ner': 13.582610695760593}
Iteration 23: Loss = {'ner': 12.083363870282987}
Iteration 24: Loss = {'ner': 20.147741353422568}
Iteration 25: Loss = {'ner': 9.179065879770587}
Iteration 26: Loss = {'ner': 7.597431983690481}
Iteration 27: Loss = {'ner': 4.043030195190952}
Iteration 28: Loss = {'ner': 7.357033733164064}
Iteration 29: Loss = {'ner': 15.533414616061972}
Iteration 30: Loss = {'ner': 8.138549260854061}
✅ تم حفظ النموذج في: skills_ner_model

In [16]:
import spacy

nlp = spacy.load("skills_ner_model")

print("✅ النموذج تم تحميله بنجاح!")

✅ النموذج تم تحميله بنجاح!

In [17]:
import spacy

nlp_skills = spacy.load("skills_ner_model")

# تجربة النموذج على نص جديد
text_to_test = " have experience in Python, JavaScript, and SQL."
doc = nlp_skills(text_to_test)

print("🔹 Extracted Skills:")
for ent in doc.ents:
    print(f"- {ent.text} ({ent.label_})")

🔹 Extracted Skills:
- JavaScript (SKILL)
- SQL (SKILL)
- . (SKILL)

In [18]:
text_to_test = "I worked with networking tools like Wireshark, Cisco Packet Tracer, and Nmap"
doc = nlp_skills(text_to_test)

print("🔹 Extracted Skills:")
for ent in doc.ents:
    print(f"- {ent.text} ({ent.label_})")

🔹 Extracted Skills:
- I (SKILL)
- Nmap (SKILL)

In [19]:
!pip install pymupdf

Collecting pymupdf
  Downloading pymupdf-1.25.3-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.25.3-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (20.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 93.0 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.25.3

In [1]:
import re
import fitz
import base64
import spacy
import csv
import nltk

# Additional libraries
nltk.download('punkt')

# Load the spaCy model for English
nlp = spacy.load('en_core_web_sm')

def load_keywords(file_path):
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        return set(row[0] for row in reader)

# ----------------------------------Extract Name----------------------------------
def extract_name(doc):
    for ent in doc.ents:
        if ent.label_ == 'PERSON':
            names = ent.text.split()
            if len(names) >= 2 and names[0].istitle() and names[1].istitle():
                return names[0], ' '.join(names[1:])
    return "", ""
# --------------------------------------------------------------------------------

# ----------------------------------Extract Email---------------------------------
def extract_email(doc):
    matcher = spacy.matcher.Matcher(nlp.vocab)
    email_pattern = [{'LIKE_EMAIL': True}]
    matcher.add('EMAIL', [email_pattern])

    matches = matcher(doc)
    for match_id, start, end in matches:
        if match_id == nlp.vocab.strings['EMAIL']:
            return doc[start:end].text
    return ""
# --------------------------------------------------------------------------------

# ----------------------------------Extract Ph No---------------------------------
def extract_contact_number_from_resume(doc):
    contact_number = None
    text = doc.text  # Extract text from SpaCy doc object
    pattern = r"\b(?:\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b"
    match = re.search(pattern, text)
    if match:
        contact_number = match.group()
    return contact_number
# --------------------------------------------------------------------------------

# --------------------------------Extract Education-------------------------------
def extract_education_from_resume(doc):
    universities = []

    # Process the document with spaCy
    doc = nlp(doc)

    # Iterate through entities and check for organizations (universities)
    for entity in doc.ents:
        if entity.label_ == "ORG" and ("university" in entity.text.lower() or "college" in entity.text.lower() or "institute" in entity.text.lower()):
            universities.append(entity.text)

    return universities
# --------------------------------------------------------------------------------

# ----------------------------------Extract Skills--------------------------------
def csv_skills(doc):
    skills_keywords = load_keywords('newSkills.csv')
    skills = set()

    for keyword in skills_keywords:
        if keyword.lower() in doc.text.lower():
            skills.add(keyword)

    return skills

nlp_skills = spacy.load('skills_ner_model')  # Load the trained NER model for skills

def extract_skills_from_ner(doc):
    non_skill_labels = {'DATE', 'TIME', 'PERCENT', 'MONEY', 'QUANTITY', 'ORDINAL', 'CARDINAL', 'EMAIL'}

    skills = set()
    for ent in nlp_skills(doc.text).ents:
        if ent.label_ == 'SKILL':
            # Check if the entity text is not in the non-skill labels set
            if ent.label_ not in non_skill_labels and not ent.text.isdigit():
                # Filter out non-alphabetic characters
                skill_text = ''.join(filter(str.isalpha, ent.text))
                if skill_text:
                    skills.add(skill_text)
    return skills

def is_valid_skill(skill_text):
    # Define criteria for valid skills (modify/add criteria as needed)
    return len(skill_text) > 1 and not any(char.isdigit() for char in skill_text)

def extract_skills(doc):
    skills_csv = csv_skills(doc)
    skills_ner = extract_skills_from_ner(doc)

    filtered_skills_csv = {skill for skill in skills_csv if is_valid_skill(skill)}
    filtered_skills_ner = {skill for skill in skills_ner if is_valid_skill(skill)}

    combined_skills = filtered_skills_csv.union(filtered_skills_ner)  # Combine filtered skills without duplicates

    return list(combined_skills)  # Return combined filtered skills as a list

# --------------------------------------------------------------------------------

# ----------------------------------Extract Major---------------------------------
def extract_major(doc):
    major_keywords = load_keywords('majors.csv')

    for keyword in major_keywords:
        if keyword.lower() in doc.text.lower():
            return keyword

    return ""
# --------------------------------------------------------------------------------

# --------------------------------Extract Experience-------------------------------
def extract_experience(doc):
    verbs = [token.text for token in doc if token.pos_ == 'VERB']

    senior_keywords = ['lead', 'manage', 'direct', 'oversee', 'supervise', 'orchestrate', 'govern']
    mid_senior_keywords = ['develop', 'design', 'analyze', 'implement', 'coordinate', 'execute', 'strategize']
    mid_junior_keywords = ['assist', 'support', 'collaborate', 'participate', 'aid', 'facilitate', 'contribute']

    if any(keyword in verbs for keyword in senior_keywords):
        level_of_experience = "Senior"
    elif any(keyword in verbs for keyword in mid_senior_keywords):
        level_of_experience = "Mid-Senior"
    elif any(keyword in verbs for keyword in mid_junior_keywords):
        level_of_experience = "Mid-Junior"
    else:
        level_of_experience = "Entry Level"

    suggested_position = suggest_position(verbs)

    return {
        'level_of_experience': level_of_experience,
        'suggested_position': suggested_position
    }

# --------------------------------------------------------------------------------


# -----------------------------------Suggestions----------------------------------
def load_positions_keywords(file_path):
    positions_keywords = {}
    with open(file_path, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            position = row['position']
            keywords = [keyword.lower()
                        for keyword in row['keywords'].split(',')]
            positions_keywords[position] = keywords
    return positions_keywords


def suggest_position(verbs):
    positions_keywords = load_positions_keywords('position.csv')
    verbs = [verb.lower() for verb in verbs]
    for position, keywords in positions_keywords.items():
        if any(keyword in verbs for keyword in keywords):
            return position

    return "Position Not Identified"


def extract_resume_info_from_pdf(uploaded_file):
    doc = fitz.open(uploaded_file)
    text = ""
    for page_num in range(doc.page_count):
        page = doc[page_num]
        text += page.get_text()
    return nlp(text)


def extract_resume_info(doc):
    first_lines = '\n'.join(doc.text.splitlines()[:10])
    first_name, last_name = extract_name(doc)
    email = extract_email(doc)
    skills = extract_skills(doc)
    degree_major = extract_major(doc)
    experience = extract_experience(doc)

    return {'first_name': first_name, 'last_name': last_name, 'email': email, 'degree_major': degree_major, 'skills': skills, 'experience': experience}

ModuleNotFoundError: No module named 'fitz'

In [22]:
x= extract_resume_info_from_pdf('CV..pdf')

In [23]:
x

0507217503 | yusra001423@gmail.com
 Linkedin :yusra-alatwi-7b967b219
:المؤهل العلمي
: الهدف الوظيفي
هدفي هو توظيف مهاراتي وخبراتي المتنوعة إلحداث تأثير
إيجابي في بيئة العمل، والمساهمة في تطويرها وتحقيق
 أسعى إلى االبتكار والتحسين المستمر، مع.األهداف المرجوة
التركيز على تحقيق نتائج فعالة وتعزيز الجودة في كل ما
.أقدمه
EDUCATIONAL QUALIFICATIONS:
 Leader of the Academic Research and Writing
Community (2023 – 2024)
Delivered in-person and online workshops in various
technical and educational fields, focusing on skill
development and fostering innovation among
participants.
Supervised and managed academic events, including
preparing and presenting professional educational
content.
Conducted training sessions and seminars aimed at
enhancing participants' understanding through
interactive methods.
Authored detailed reports for events and activities.
يسرا خميس العطوي
 جامعة تبوك
  )تقنية المعلومات( بكالوريوس كلية الحسابات
2024   -  2020
 4.04/5 : معدل

:الدورات والشهادات
Class Dojo  (Coursera ) إدارة الصفوف الدراسية باستخدام أداة
)  منصة كورسيرا(دورة اسس التدريس
) منصة أعناب لتطوير المعلمين( دورة طرق التدريس الحديثة
)Coursera( الذكاء العاطفي واالجتماعي
)جامعة تبوك( شهادة قائد مميز
)Cisco( شهادة مقدمة في األمن السيبراني وإنترنت األشياء
)Python معهد( Python أساسيات لغة
CAREER OBJECTIVE:
University of Tabuk
Bachelor’s Degree in IT (College of Computing)
2020 - 2024
GPA: 4.04/5
My goal is to leverage my diverse skills and experiences to
make a positive impact in the work environment, contributing
to its development and achieving the desired objectives. I
strive for innovation and continuous improvement, with a focus
on achieving effective results and enhancing quality in
everything I deliver.
: الخبرات
)2024  – 2023 ( قائد مجتمع البحث والكتابة األكاديمية
تقديم ورش عمل حضورية وعن ُبعد في مجاالت تقنية وتعليمية
مختلفة، مع التركيز على تطوير مهارات المشاركين وتحفيزهم على
.االبتكار
اإلشراف على تنظيم وإدارة فعاليات أكاديمية تتضمن إعداد
.محتوى تعليمي وتقديمه بشكل احترافي
قيادة جلسات تدريبية وندوات تهدف إلى تعزيز الفهم لدى
.المتدربين باستخدام أساليب تفاعلية
. كتابة تقارير تفصيلية
 ) AID ( تطوير مشروع التخرج
تصميم وتطوير نظام الكتشاف الثغرات البرمجية باستخدام الذكاء
.االصطناعي لتعزيز تدابير األمن السيبراني
.تحليل البيانات وتدريب النماذج
EXPERIENCE:
COURSES AND CERTIFICATIONS:

Classroom Management with Class Dojo (Coursera)
Fundamentals of Teaching (Coursera)
Modern Teaching Methods (Aanaab Platform for
Teachers)
Emotional and Social Intelligence (Coursera)
Distinguished Leader Award (University of Tabuk)
Introduction to Cybersecurity and IoT (Cisco)
Python Essentials (Python Institute)
 تقنية
.Canva وPowerPoint  تصميم وتقديم العروض باستخدام•
.Microsoft Teams وGoogle  إدارة األنظمة اإللكترونية مثل•
. البرمجة لتطوير حلول تقنية مبسطة تدعم سير العمل•
. إدارة الحمالت اإلعالنية والتسويقية•
 ناعمه
. التحدث واإللقاء بوضوح وجاذبية، مع نقل المعلومات بشكل مؤثر ومنظم•
. بناء عالقات إيجابية مع الزمالء والعمالء وتحفيزهم نحو تحقيق األهداف•
 أتمتع بسرعة ودقة في الكتابة على لوحة المفاتيح، مما يضمن إنجاز المهام•
.بكفاءة عالية
. أتميز بابتكار أفكار جديدة لتصميم المحتوى وتحسين العمليات•
. أجيد العمل الجماعي وبناء بيئة إيجابية تحقق األهداف المشتركة•
:المهارات
: اللغات
Arabic: Excellent
English: Intermediate
SKILLS
Technical Skills
• Designing and delivering presentations using PowerPoint
and Canva.
• Managing electronic systems such as Google and
Microsoft Teams.
• Programming to develop streamlined technical solutions
that support workflow.
• Managing advertising and marketing campaigns.
Soft Skills
• Speaking and presenting clearly and engagingly, effectively
and systematically conveying information.
• Building positive relationships with colleagues and clients,
motivating them toward achieving goals.
• Typing with speed and accuracy, ensuring high efficiency in
task completion.
• Demonstrating creativity in developing new content designs
and improving processes.
• Excelling in teamwork and fostering a positive environment
that achieves shared objectives.
LANGUAGES
ممتازه : العربية
متوسطة : االنجليزية

In [24]:

import google.generativeai as genai
# change the api to student API
genai.configure(api_key = 'AIzaSyC9z9vVcz6Nwo1O-i1EZsHkT571ZztS_i8')
model = genai.GenerativeModel(model_name='gemini-2.0-flash')

In [25]:
prompt = f"""
Based on the resume details below, suggest the most suitable job roles for this candidate.
Consider their skills, experience, education, and certifications.

Resume:
{x}
"""

# 🔹 إرسال الطلب إلى النموذج
response = model.generate_content(prompt)

# 🔹 طباعة النتيجة
print("✅ Suggested Job Roles:\n")
print(response.text)

✅ Suggested Job Roles:

Based on Yusra's resume, here's a breakdown of suitable job roles, categorized by how well they align with her skills and experience:

**Highly Suitable Roles:**

*   **Training and Development Specialist:** Her experience as a Leader of the Academic Research and Writing Community, delivering workshops, supervising events, and conducting training sessions directly aligns with this role. She also has certifications relevant to teaching and emotional intelligence.
*   **Educational Content Developer/Creator:** Her experience in preparing and presenting professional educational content, combined with her design skills using Canva and PowerPoint, makes her a strong candidate for creating educational materials.
*   **Academic Advisor/Tutor:** Her leadership role, workshop experience, and strong GPA (4.04/5) suggest a strong understanding of academic principles and the ability to guide and support students.
*   **Instructional Designer:** Leveraging her IT background, teaching certifications, and content creation abilities, she could design engaging and effective learning experiences using technology.

**Suitable Roles (with some development potentially needed):**

*   **Junior Cybersecurity Analyst:** With her Bachelor's in IT and the Cisco Cybersecurity and IoT certification, she has a foundational understanding of cybersecurity. A junior role would allow her to gain practical experience.
*   **IT Support Specialist/Technical Trainer:** Her IT degree, coupled with her experience in managing electronic systems like Google and Microsoft Teams, makes her suitable for providing technical support or training users on software/systems.
*   **Marketing/Communications Assistant (with a technical focus):** Her experience managing advertising and marketing campaigns, combined with her technical skills, could be valuable in a role that requires creating and delivering technical content.
*   **Project Assistant/Coordinator:** Her leadership experience, report writing skills, and teamwork abilities make her a candidate for assisting in project management, particularly in technical or educational projects.
*   **Technical Writer:** Combining her IT background and report-writing experience, she could document technical processes, create user manuals, or develop online help systems.

**Roles Less Suitable (requiring significant upskilling):**

*   **Software Developer/Programmer:** While she has Python Essentials certification, a more in-depth understanding and practical experience in software development would be necessary.
*   **Data Analyst:** Her graduation project involving data analysis and AI is a starting point, but further training and experience in data analysis tools and techniques would be needed.
*   **Network Engineer:** Her cybersecurity certification is a good start, but dedicated networking certifications (like CCNA) and experience would be required.

**Key Strengths to Highlight in Applications:**

*   **Leadership and Communication:** Her experience as a leader and workshop facilitator demonstrates strong communication, presentation, and interpersonal skills.
*   **Technical Proficiency:** Her IT degree and certifications in cybersecurity and Python provide a solid technical foundation.
*   **Academic Excellence:** Her high GPA shows diligence and a strong grasp of academic concepts.
*   **Creativity and Innovation:** Her resume explicitly mentions her creativity in content design and process improvement.
*   **Commitment to Continuous Improvement:** Her career objective emphasizes her desire for innovation and continuous improvement.

**Recommendations:**

*   **Improve English Proficiency:** While she lists intermediate English skills, further developing her English would significantly broaden her job opportunities, especially in international companies or roles requiring collaboration with global teams.
*   **Tailor Resume:**  She should tailor her resume to each specific job application, highlighting the skills and experiences most relevant to the target role.  For example, if applying for a Cybersecurity Analyst position, she should emphasize her Cisco certification and graduation project details.  If applying for a Training Specialist role, she should emphasize her workshop experience and teaching certifications.
*   **Build a Portfolio:**  Creating a portfolio of her work (e.g., sample presentations, training materials, code snippets, project reports) would be beneficial to showcase her skills and abilities to potential employers.

In [26]:
# 🔹 إنشاء الـ prompt لطلب التقييم
prompt = f"""
Evaluate the resume below on a scale of 100.
Consider factors such as skills, experience, education, certifications, and overall suitability for job roles.
Provide a brief explanation of the score.

Resume:
{x}

Output format:
- Score: XX/100
- Explanation: [Brief reasoning]
"""

# 🔹 إرسال الطلب إلى النموذج
response = model.generate_content(prompt)

# 🔹 طباعة النتيجة
print("✅ Resume Evaluation:\n")
print(response.text)

✅ Resume Evaluation:

- **Score: 78/100**
- **Explanation:**

This resume shows a lot of potential, particularly given the recent graduation date. The GPA is excellent. The "Leader of the Academic Research and Writing Community" experience is a strong highlight, demonstrating leadership, training, and presentation skills. The listed courses and certifications are relevant and showcase a commitment to learning. The skills section is adequately detailed, covering both technical and soft skills.

However, there are some areas for improvement that are dragging down the overall score:

*   **Formatting and Readability:** The mixed use of Arabic and English makes the resume harder to read for English-speaking employers. Consistency is crucial.
*   **Objective Statement:** The objective statement is somewhat generic. It should be tailored to specific job roles and highlight what the candidate offers to a potential employer.
*   **Experience Detail:** The experience descriptions should be more results-oriented. Instead of just stating tasks, quantify achievements whenever possible (e.g., "Increased workshop attendance by X%"). The graduation project could use more detail about the AI and cybersecurity aspects.
*   **Language Proficiency:** "Intermediate" English could be a barrier for roles requiring strong communication skills.
*   **Contact Information:** While the email and LinkedIn are listed, they are not very prominent. The phone number is also presented in an unconventional format.
*   **Inconsistencies:** The placement of the experience and education sections is inconsistent between the Arabic and English versions.

If the resume were consistently in English, with more detailed and quantified experience descriptions, and a targeted objective statement, it could easily score in the 85-90 range.

In [27]:
import shutil
shutil.make_archive('my_folder', 'zip', 'skills_ner_model')

'/content/my_folder.zip'